### PR TITLE
fix params merging

### PR DESCRIPTION
**Pull request by gokatz**
First of all, thanks for the library. It saved me a lot of time :) 

The default params overriding the passed params. Hence the fix.

### CODE REVIEW

**Comment by marcolink** [comment]
Looks good 👍🏻

**Comment by gokatz** [comment]
Thanks a bunch @marcolink Looks like the release has failed: https://github.com/marcolink/redash-tools/actions/runs/4561854709/jobs/8048330888 (token expiry?). Any idea about this?

**Comment by marcolink** [comment]
@gokatz its released!

**Comment by gokatz** [comment]
Awesome. thanks :)

**Pull request merged**
